language: php

sudo: false

php:
    - 5.3
    - 5.4
    - 5.5
    - 5.6
    - 7.0
    - hhvm

before_install:
    - composer self-update

install:
    - composer install --prefer-source --no-interaction --dev

script: vendor/bin/phpunit --coverage-html coverage

matrix:
    allow_failures:
        - php: 7.0
        - php: hhvm
    fast_finish: true
